name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # or whichever branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install # or any other command to install dependencies

      - name: Zip Lambda Function
        run: zip -r function.zip . # Adjust this command based on your project structure

      - name: Upload to AWS Lambda
        uses: aws-actions/aws-cli-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          command: >
            lambda update-function-code
            --function-name willItRain-2
            --zip-file fileb://function.zip
